### ISSUE TITLE
There is a Lab 9 Due!!

### ISSUE THREAD

**Issue by estarkey7** [estarkey7/CSIS3700_Project2#5]
I just logged in and found out there is a Lab 9 Due 4/30/2015!!

**Comment by nmroncone** [comment]
oh man, so I guess we did have class then? I hope he'll accept it Tuesday before the final. Also did you see my email about the enemy.cpp file? I can't compile the program now because I think the enemy.cpp is not included with the source files in the synced version.

Thanks,
            Nick Roncone

On May 1, 2015, at 12:18 AM, Ed Starkey <notifications@github.com<mailto:notifications@github.com>> wrote:

I just logged in and found out there is a Lab 9 Due 4/30/2015!!

##

**Comment by estarkey7** [comment]
Oh crap!! I am at work and don't have the files on me. I will hack something in so it ca be rebuilt.

**Comment by nmroncone** [comment]
I can't get the bug images or enemy files to sync because it said there was a conflict. I tried to commit my changes first but now it says it's synced but still without the files. How do I revert back to your last commit?

Thanks,
            Nick Roncone

On May 1, 2015, at 12:42 PM, Ed Starkey <notifications@github.com<mailto:notifications@github.com>> wrote:

Oh crap!! I am at work and don't have the files on me. I will hack something in so it ca be rebuilt.

##
